### ISSUE TITLE
(tlg0557.tlg002) -- converting sections from milestones to divs

### ISSUE THREAD

**Issue by gregorycrane** [PerseusDL/canonical-greekLit#1060]
We have divs for the chapters but still have milestones for sections.

[there are also places where i pick up errors, esp. places where the automated system did not pick up the right section break.]

**Comment by gregorycrane** [comment]
I added:
* <div type="edition" xml:lang="grc" n="urn:cts:greekLit:tlg0557.tlg002.perseus-grc2"> ... </div>
* the __CTS__.xml files for tlg0557 and tlg0557.tlg003
I will now provoke another hooktest and see how far I get.

**Comment by lcerrato** [comment]
Let me know if you want me to bump the files and comment on the cts work file format. We have some recommended naming formats to deal with inconsistencies in titles.

It looks like the pull request for this is more than tlg0557.tlg002 (you have tlg0557.tlg001 and tlg0557.tlg003 as well) is that the case?

**Comment by gregorycrane** [comment]
I am having serious problems because I changed __CTS__.xml to __cts__.xml. I am going to create a new issue  and use that new branch to fix that problem.

**Comment by lcerrato** [comment]
closed via #1068 see also #1066
