### ISSUE TITLE
Convert tlg0032.tlg002

### ISSUE THREAD

**Issue by balmas** [PerseusDL/canonical-greekLit#112]
this is needed for Digital Milliet

When converted, we need to update the Digital Milliet data to use the new version.

**Comment by lcerrato** [comment]
see also https://github.com/PerseusDL/catalog_data/issues/74

**Comment by lcerrato** [comment]
added quotes to file; fixed lang digits in cts work file

**Comment by lcerrato** [comment]
fixed via #123
