### ISSUE TITLE
remove texts /tlg0019.tlg007.perseus-engX.xml

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/canonical-greekLit#117]
Unless we can prove otherwise, this is likely not suitable for this repo. 
Otherwise, we need a better text header.
It doesn't look like there was much success in cataloging this? @AlisonBabeu

**Comment by AlisonBabeu** [comment]
I did not have much luck as there were various published editions of Lysistrata by Jack Lindsay none of which were clearly in the public domain or viewable online so I went very generic in terms of the edition. It also looks like I created a catalog record for this work quite a long time ago before I even started research text histories. You are quite right we should probably remove it.

**Comment by lcerrato** [comment]
Greg has asserted it should be removed. It was reprinted by Floating Press in 2012 in its entirety, suggesting it is available. I may look at a hard copy if I can buy one.

**Comment by lcerrato** [comment]
Hard copy has no copyright assertion, just a "published by" note.

**Comment by lcerrato** [comment]
Project Gutenberg asserts public domain http://www.gutenberg.org/ebooks/7700

**Comment by lcerrato** [comment]
I'm going to leave this as is for now.
