### ISSUE TITLE
(tlg0031.tlg001.perseus-grc2.xml) 23.39 typographical error

### ISSUE THREAD

**Issue by verite** [PerseusDL/canonical-greekLit#1227]
https://github.com/PerseusDL/canonical-greekLit/blob/28fef413d201e97cd5e7157c1c0583849eb173cf/data/tlg0031/tlg001/tlg0031.tlg001.perseus-grc2.xml#L5085

blank verse
 \<div type="textpart" subtype="verse" n="39"/>\</div>

**Comment by lcerrato** [comment]
23.39 is not marked in the print edition — this has resulted in the omission
https://archive.org/details/newtestamentino00west/page/112/mode/2up
