### ISSUE TITLE
(tlg0031.tlg001.perseus-grc2.xml) 22.8

### ISSUE THREAD

**Issue by verite** [PerseusDL/canonical-greekLit#1229]
https://github.com/PerseusDL/canonical-greekLit/blob/28fef413d201e97cd5e7157c1c0583849eb173cf/data/tlg0031/tlg001/tlg0031.tlg001.perseus-grc2.xml#L4573

MATTHIEU 22 8
οἱ	δὲ	κεκλημένοι	οὐκ	ἦσαν	ἄξιοι·	ἕτοιμός	ἐστιν,
ἕτοιμός	ἐστιν,	οἱ	δὲ	κεκλημένοι	οὐκ	ἦσαν	ἄξιοι·

**Comment by lcerrato** [comment]
incorrect verse break
