### ISSUE TITLE
WH : data/tlg0031/tlg002/tlg0031.tlg002.perseus-grc2.xml#L1150

### ISSUE THREAD

**Issue by verite** [PerseusDL/canonical-greekLit#1232]
https://github.com/PerseusDL/canonical-greekLit/blob/28fef413d201e97cd5e7157c1c0583849eb173cf/data/tlg0031/tlg002/tlg0031.tlg002.perseus-grc2.xml#L1150

MARC 5 7
δε
σε

**Comment by lcerrato** [comment]
https://archive.org/details/newtestamentino00west/page/162/mode/2up
