### ISSUE TITLE
(tlg0560.tlg001.perseus-grc1.xml) EpiDoc and CTS conversion

### ISSUE THREAD

**Issue by mkonieczny9805** [PerseusDL/canonical-greekLit#1237]
@lcerrato It looks like (pseudo)-Longinus hasn't yet made the transition from Perseus. Wonder if I could claim this file for conversion. If so could you "bump" the URN?

**Comment by lcerrato** [comment]
@mkonieczny9805 
The URN is bumped and this looks good!
