### ISSUE TITLE
Unable to parse tlg0627.tlg046.perseus-grc1.xml

### ISSUE THREAD

**Issue by sonofmun** [PerseusDL/canonical-greekLit#13]

**Comment by sonofmun** [comment]
Using lxml.etree.fromstring()

**Comment by srdee** [comment]
@sonofmun there's a lot of transitional files in these repos, many of which aren't EpiDoc and some of which aren't valid XML

**Comment by srdee** [comment]
@sonofmun  for details see the tracking files: e.g. https://github.com/PerseusDL/canonical-greekLit/blob/master/data/tlg0627/tlg046/tlg0627.tlg046.perseus-grc1.tracking.json

or the combined ones, e.g. https://github.com/PerseusDL/canonical-greekLit/blob/master/canonical-greekLit.tracking.json

**Comment by sonofmun** [comment]
I figured as much.  If it is not helpful for me to put in which files I 
cannot parse when I get to them, then I won't.  But I thought this would 
be a good way to keep track of where we have invalid xml.

On 09.07.2015 16:54, srdee wrote:
>
> @sonofmun <https://github.com/sonofmun> there's a lot of transitional 
> files in these repos, many of which aren't EpiDoc and some of which 
> aren't valid XML
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/PerseusDL/canonical-greekLit/issues/13#issuecomment-120013082>.
>

-- 
Matthew Munson
Researcher
Alexander von Humboldt Chair of Digital Humanities
Universität Leipzig, Institut für Informatik
Augustusplatz 10, 04109 Leipzig
Deutschland

**Comment by srdee** [comment]
Unless it differs from the tracking file, there's no need! (I.e. if you
can parse it and the tracking file says it's invalid, or if you can't
and the tracking file says it's valid)

**Comment by sonofmun** [comment]
Cool.  Good to know.  I will not be checking the tracking files for the 
ones I can parse.  But if I have trouble, I will check there before 
submitting an issue.

On 09.07.2015 16:58, srdee wrote:
> Unless it differs from the tracking file, there's no need! (I.e. if you
> can parse it and the tracking file says it's invalid, or if you can't
> and the tracking file says it's valid)
>
> On 7/9/15 8:57 AM, sonofmun wrote:
> > I figured as much. If it is not helpful for me to put in which files I
> > cannot parse when I get to them, then I won't. But I thought this would
> > be a good way to keep track of where we have invalid xml.
> >
> > On 09.07.2015 16:54, srdee wrote:
> >>
> >> @sonofmun <https://github.com/sonofmun> there's a lot of transitional
> >> files in these repos, many of which aren't EpiDoc and some of which
> >> aren't valid XML
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> 
> <https://github.com/PerseusDL/canonical-greekLit/issues/13#issuecomment-120013082>.
> >>
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/PerseusDL/canonical-greekLit/issues/13#issuecomment-120016308>.
>

-- 
Matthew Munson
Researcher
Alexander von Humboldt Chair of Digital Humanities
Universität Leipzig, Institut für Informatik
Augustusplatz 10, 04109 Leipzig
Deutschland
