### ISSUE TITLE
(tlg7000.tlg001.perseus-grc2.xml) wrong word - typo

### ISSUE THREAD

**Issue by PonteIneptique** [PerseusDL/canonical-greekLit#131]
NB 7.11.1

The original reads 

```xml
<l n="1">Ὁ γλυκὺς Ἠρίννης οὗτος πόνος, οὐχὶ πολὺς μέν,</l>
``` 

while our version has a typo

```xml
<l n="1">γλυκὺς γλυκὺς Ἠρίννης οὗτος πόνος, οὐχὶ πολὺς μέν,</l>
``` 

as per https://archive.org/stream/greekanthology02newyuoft#page/8/mode/2up

**Comment by lcerrato** [comment]
note there are many errors in this work; this was prepared via in house OCR and has a high level of textual problems.

**Comment by lcerrato** [comment]
added to #122
