### ISSUE TITLE
(tlg0016) Herodotus header and CTS info

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/canonical-greekLit#1323]
Header info in Herodotus files is inconsistent with catalog (dates) and cts needs review.

**Comment by AlisonBabeu** [comment]
hey @lcerrato I'm closing out clearing some issues can I close this one?

**Comment by lcerrato** [comment]
@AlisonBabeu 
Yes, if you think it's fixed. Next time use "fix #dddd" in the pull request and it will be closed automatically.
