### ISSUE TITLE
tlg0062.tlg071.perseus-grc1.xml, Lucian Podagra - missing three quarters of text

### ISSUE THREAD

**Issue by helmadik** [PerseusDL/canonical-greekLit#1342]
This text goes only through line 78 (page 444 of Teubner volume) of 334 lines total (page 454 of Teubner vol III).
@gregorycrane, any chance of an OCR version of these pages hiding somewhere in your or Bruce R's files? Clearly, I can't get enough of Lucian:-) https://archive.org/details/lucianisamosate04jacogoog/page/444/mode/2up for Jacobitz.

**Comment by lcerrato** [comment]
@helmadik @gregorycrane @broberston
Hi Helma,
I can probably add a few pages to Lace to do this or I can run them on my local instantiation. (Usually we run who volumes so I'm not sure how to hack it to do just a few pages), if you have the inclination to do the OCR correction. 
We don't have any current student intern programs running now (or any employees) so I don't have anyone to do this immediately. 

I dug around and found the raw file, but it was not corrected by the data entry people.  So it was probably run in house but we either never sent it out for correction or probably lost it when it came back. The files were split oddly into page segments so I suspect the workflow was choppy.

Here is what I found.
[lucian_446-454_0062.071.txt](https://github.com/PerseusDL/canonical-greekLit/files/9002410/lucian_446-454_0062.071.txt)
.

**Comment by helmadik** [comment]
Dear Lisa, 
Fabulous, thank you for finding this! It's only 300 lines, and this is the finish line for what is accepted as genuine Lucian, so it would be a pity to not take it on, choppy as it is. BTW, this batch of files in canonical-greekLit says it was keyboarded from the Teubner - not an OCR output, like the 1stKGreek Lucian files - just in case that helps you find this in some other set of files.. Either way, I'll get to work on this, though.

**Comment by lcerrato** [comment]
@helmadik 
The headers for many of these works added in that period are just copied from other files and very often incomplete and inaccurate.  This was in an Ocropus folder and others were in back from data entry folders, and I remember the workflow on these files.
When they are converted, we review the headers for accuracy and these sorts of details.

Thanks for noticing this!

**Comment by lcerrato** [comment]
fixed via https://github.com/PerseusDL/canonical-greekLit/pull/1424
