### ISSUE TITLE
Chariton of Aphrodisios should be Chariton of Aphrodisias

### ISSUE THREAD

**Issue by PonteIneptique** [PerseusDL/canonical-greekLit#136]
While Aphrodisios seems to be attested on some websites (Did not check the sources), it seems that the main spelling is Aphrodisias :) ( https://en.wikipedia.org/wiki/Chariton)

**Comment by lcerrato** [comment]
@PonteIneptique Is this a textual error or a catalog error? I see alternate spellings in the catalog. 
The only thing that would fall in this repo is the text group file you created, correct?
I could certainly correct that but I'd defer to the catalog first.

If the catalog data is the source of the confusion, an issue needs to be created in that repo, as well. Happy to do so, but was unsure of the scope of the requested corrections.

**Comment by AlisonBabeu** [comment]
I do have both variants of the name spelling captured in the authority file (or MADS) record so that people searching for the authors will find both instances in the catalog so I don't think there is anything that needs to be changed in catalog_data at this point.

**Comment by lcerrato** [comment]
I wonder if Aphrodisios is an attested variant of Aphrodisias? This looks like an 18thC edition is the source for this spelling, but it doesn't appear anywhere else. It does not appear that the place uses the "o" spelling at all.
Regardless, this report pertains only to the textgroup metadata file /tlg0554/__cts__.xml

**Comment by PonteIneptique** [comment]
Agree with @lcerrato that this spelling is uniquely related to the 18th century edition.
The issue is, with the current state of the catalog, you cannot find Chariton using Aphrodisias.

**Comment by AlisonBabeu** [comment]
On this last point, I would have to disagree. If you search for Aphrodisias
in the Perseus Catalog:
http://catalog.perseus.org/?utf8=%E2%9C%93&search_field=all_fields&q=Aphrodisias
the second result is for Chariton.

**Comment by PonteIneptique** [comment]
You're totally right. I must have done something wrong... My bad :)

**Comment by AlisonBabeu** [comment]
Perhaps the catalog system just decided to trick you :),
I swear that sometimes I search the catalog and don't get the same results
twice!

**Comment by lcerrato** [comment]
That's what makes it fun!
If we want the text group metadata file to reflect the "a" spelling, I am happy to add it to the typos thread. 
What's the vote? Leave or change?

**Comment by PonteIneptique** [comment]
Even so leave seems to be hype right now in Europe, I would vote for change.

**Comment by lcerrato** [comment]
moved to #122
