### ISSUE TITLE
':' instead of '·'

### ISSUE THREAD

**Issue by kristoffer-paulsson** [PerseusDL/canonical-greekLit#1364]
Hi PDL, thanks for a great library of textual resources in Koine. I have a big interest as a private person in bible translation and think of developing some type of nltk package for koine, that makes PDL invaluable for me. I like when text and code are perfectly formatted so I write some scripts to analyze Koine in batch.

I found a number of places where there seem to be ':' instead of '·'.
As I understand probably the colons are supposed to be bullet points.

Here is a batch of files having colons instead in the corpora. See below.

1679 number of ':' in file canonical-greekLit/data/tlg0003/tlg001/tlg0003.tlg001.perseus-grc2.xml
9 number of ':' in file canonical-greekLit/data/tlg0007/tlg001/tlg0007.tlg001.perseus-grc2.xml
7 number of ':' in file canonical-greekLit/data/tlg0007/tlg007/tlg0007.tlg007.perseus-grc2.xml
39 number of ':' in file canonical-greekLit/data/tlg0007/tlg012/tlg0007.tlg012.perseus-grc2.xml
5 number of ':' in file canonical-greekLit/data/tlg0007/tlg047/tlg0007.tlg047.perseus-grc2.xml
234 number of ':' in file canonical-greekLit/data/tlg0007/tlg092/tlg0007.tlg092.perseus-grc2.xml
5390 number of ':' in file canonical-greekLit/data/tlg0008/tlg001/tlg0008.tlg001.perseus-grc4.xml
43 number of ':' in file canonical-greekLit/data/tlg0017/tlg001/tlg0017.tlg001.perseus-grc1.xml
41 number of ':' in file canonical-greekLit/data/tlg0017/tlg002/tlg0017.tlg002.perseus-grc1.xml
63 number of ':' in file canonical-greekLit/data/tlg0017/tlg003/tlg0017.tlg003.perseus-grc1.xml
21 number of ':' in file canonical-greekLit/data/tlg0017/tlg004/tlg0017.tlg004.perseus-grc1.xml
66 number of ':' in file canonical-greekLit/data/tlg0017/tlg005/tlg0017.tlg005.perseus-grc1.xml
55 number of ':' in file canonical-greekLit/data/tlg0017/tlg006/tlg0017.tlg006.perseus-grc1.xml
35 number of ':' in file canonical-greekLit/data/tlg0017/tlg007/tlg0017.tlg007.perseus-grc1.xml
45 number of ':' in file canonical-greekLit/data/tlg0017/tlg008/tlg0017.tlg008.perseus-grc1.xml
38 number of ':' in file canonical-greekLit/data/tlg0017/tlg009/tlg0017.tlg009.perseus-grc1.xml
21 number of ':' in file canonical-greekLit/data/tlg0017/tlg010/tlg0017.tlg010.perseus-grc1.xml
40 number of ':' in file canonical-greekLit/data/tlg0017/tlg011/tlg0017.tlg011.perseus-grc1.xml
22 number of ':' in file canonical-greekLit/data/tlg0017/tlg012/tlg0017.tlg012.perseus-grc1.xml
44 number of ':' in file canonical-greekLit/data/tlg0024/tlg001/tlg0024.tlg001.perseus-grc1.xml
115 number of ':' in file canonical-greekLit/data/tlg0026/tlg001/tlg0026.tlg001.perseus-grc1.xml
148 number of ':' in file canonical-greekLit/data/tlg0026/tlg002/tlg0026.tlg002.perseus-grc1.xml
195 number of ':' in file canonical-greekLit/data/tlg0026/tlg003/tlg0026.tlg003.perseus-grc1.xml
158 number of ':' in file canonical-greekLit/data/tlg0027/tlg001/tlg0027.tlg001.perseus-grc1.xml
24 number of ':' in file canonical-greekLit/data/tlg0027/tlg002/tlg0027.tlg002.perseus-grc1.xml
73 number of ':' in file canonical-greekLit/data/tlg0027/tlg003/tlg0027.tlg003.perseus-grc1.xml
74 number of ':' in file canonical-greekLit/data/tlg0027/tlg004/tlg0027.tlg004.perseus-grc1.xml
18 number of ':' in file canonical-greekLit/data/tlg0028/tlg001/tlg0028.tlg001.perseus-grc1.xml
29 number of ':' in file canonical-greekLit/data/tlg0028/tlg002/tlg0028.tlg002.perseus-grc1.xml
37 number of ':' in file canonical-greekLit/data/tlg0028/tlg003/tlg0028.tlg003.perseus-grc1.xml
19 number of ':' in file canonical-greekLit/data/tlg0028/tlg004/tlg0028.tlg004.perseus-grc1.xml
116 number of ':' in file canonical-greekLit/data/tlg0028/tlg005/tlg0028.tlg005.perseus-grc1.xml
74 number of ':' in file canonical-greekLit/data/tlg0028/tlg006/tlg0028.tlg006.perseus-grc1.xml
203 number of ':' in file canonical-greekLit/data/tlg0029/tlg004/tlg0029.tlg004.perseus-grc1.xml
53 number of ':' in file canonical-greekLit/data/tlg0029/tlg005/tlg0029.tlg005.perseus-grc1.xml
40 number of ':' in file canonical-greekLit/data/tlg0029/tlg006/tlg0029.tlg006.perseus-grc1.xml
25 number of ':' in file canonical-greekLit/data/tlg0030/tlg001/tlg0030.tlg001.perseus-grc1.xml
17 number of ':' in file canonical-greekLit/data/tlg0030/tlg002/tlg0030.tlg002.perseus-grc1.xml
41 number of ':' in file canonical-greekLit/data/tlg0030/tlg003/tlg0030.tlg003.perseus-grc1.xml
20 number of ':' in file canonical-greekLit/data/tlg0030/tlg004/tlg0030.tlg004.perseus-grc1.xml
18 number of ':' in file canonical-greekLit/data/tlg0030/tlg005/tlg0030.tlg005.perseus-grc1.xml
43 number of ':' in file canonical-greekLit/data/tlg0030/tlg006/tlg0030.tlg006.perseus-grc1.xml
261 number of ':' in file canonical-greekLit/data/tlg0034/tlg001/tlg0034.tlg001.perseus-grc1.xml
1 number of ':' in file canonical-greekLit/data/tlg0060/tlg001/tlg0060.tlg001.perseus-grc3.xml
1 number of ':' in file canonical-greekLit/data/tlg0099/tlg001/tlg0099.tlg001.perseus-grc1.xml
7 number of ':' in file canonical-greekLit/data/tlg0385/tlg001/tlg0385.tlg001.perseus-grc1.xml
3 number of ':' in file canonical-greekLit/data/tlg0526/tlg001/tlg0526.tlg001.perseus-grc1.xml
2 number of ':' in file canonical-greekLit/data/tlg0533/tlg004/tlg0533.tlg004.perseus-grc1.xml
22 number of ':' in file canonical-greekLit/data/tlg0535/tlg001/tlg0535.tlg001.perseus-grc1.xml
14 number of ':' in file canonical-greekLit/data/tlg0555/tlg001/tlg0555.tlg001.perseus-grc1.xml
6 number of ':' in file canonical-greekLit/data/tlg0555/tlg006/tlg0555.tlg006.perseus-grc1.xml
1 number of ':' in file canonical-greekLit/data/tlg0555/tlg008/tlg0555.tlg008.perseus-grc1.xml
1 number of ':' in file canonical-greekLit/data/tlg0653/tlg001/tlg0653.tlg001.perseus-grc1.xml
8 number of ':' in file canonical-greekLit/data/tlg0719/tlg001/tlg0719.tlg001.perseus-grc1.xml
5 number of ':' in file canonical-greekLit/data/tlg0719/tlg003/tlg0719.tlg003.perseus-grc1.xml
517 number of ':' in file canonical-greekLit/data/tlg1389/tlg001/tlg1389.tlg001.perseus-grc2.xml
99 number of ':' in file canonical-greekLit/data/tlg2003/tlg001/tlg2003.tlg001.perseus-grc1.xml
78 number of ':' in file canonical-greekLit/data/tlg2003/tlg002/tlg2003.tlg002.perseus-grc1.xml
155 number of ':' in file canonical-greekLit/data/tlg2003/tlg003/tlg2003.tlg003.perseus-grc1.xml
38 number of ':' in file canonical-greekLit/data/tlg2003/tlg004/tlg2003.tlg004.perseus-grc1.xml
74 number of ':' in file canonical-greekLit/data/tlg2003/tlg005/tlg2003.tlg005.perseus-grc1.xml
38 number of ':' in file canonical-greekLit/data/tlg2003/tlg006/tlg2003.tlg006.perseus-grc1.xml
115 number of ':' in file canonical-greekLit/data/tlg2003/tlg007/tlg2003.tlg007.perseus-grc1.xml
72 number of ':' in file canonical-greekLit/data/tlg2003/tlg008/tlg2003.tlg008.perseus-grc1.xml
89 number of ':' in file canonical-greekLit/data/tlg2003/tlg009/tlg2003.tlg009.perseus-grc1.xml
94 number of ':' in file canonical-greekLit/data/tlg2003/tlg010/tlg2003.tlg010.perseus-grc1.xml
67 number of ':' in file canonical-greekLit/data/tlg2003/tlg011/tlg2003.tlg011.perseus-grc1.xml
121 number of ':' in file canonical-greekLit/data/tlg2003/tlg012/tlg2003.tlg012.perseus-grc1.xml
61 number of ':' in file canonical-greekLit/data/tlg2040/tlg002/tlg2040.tlg002.perseus-grc1.xml
11 number of ':' in file canonical-greekLit/data/tlg2040/tlg004/tlg2040.tlg004.perseus-grc1.xml
38 number of ':' in file canonical-greekLit/data/tlg2045/tlg001/tlg2045.tlg001.perseus-grc1.xml
1 number of ':' in file canonical-greekLit/data/tlg2046/tlg001/tlg2046.tlg001.perseus-grc1.xml
3 number of ':' in file canonical-greekLit/data/tlg7000/tlg001/tlg7000.tlg001.perseus-grc5.xml

**Comment by lcerrato** [comment]
@kristoffer-paulsson 
Thank you for bringing this to our attention.
I am currently in the process of fixing some encoding inconsistencies throughout this repository. Unfortunately, depending on how the conversion was done, there are many beta code to Unicode issues. I have seen the Greek semi-colon issue previously. I will have to look at some pattern matching to see if it can be addressed. There are actually several sets of issues with bad characters that are found in these files.

Most of these files, however, have not been reviewed since their conversion. Any file ending in "grc1" is unlikely to have been reviewed for correct encoding and updated to CTS and EpiDoc. In general, at the time of this updating, we look at the file content to check for these types of inconsistencies. 

While I am happy to address this issue throughout the repo, it is, in general, typically a sign that there are other things in these files that we need to check and update.  The Greek NT files have several quality problems that are documented in these issues that go beyond this and will require a more comprehensive proofreading.

Please follow this issue (and others) for additional updates. More pull requests on this repository will be forthcoming.

Best,
Lisa
