### ISSUE TITLE
(tlg0099.tlg001.perseus-grc2) XML tags have extra slashes

### ISSUE THREAD

**Issue by TickleForce** [PerseusDL/canonical-greekLit#1372]
A recent commit introduced extra closing "/" slashes in several XML tags.

[Here](https://github.com/PerseusDL/canonical-greekLit/commit/e3adb7d4b91b843c60fa28acf00c61b0b6c8c153#diff-24b1543498e3dd10f7283d95206c30f69b91c36fa3bd0fdd77c1f1ecccb27cd5R349) is one example.

This issue also affects other files that were modified in the commit.

The XML parser I was using threw an error while parsing these files. My solution was to simply automatically replace all occurrences of `//>` with `/>`.

Another issues introduced in the same commit in (tlg0005.tlg001) on line 2632 is that `<q>` got replaced with `<q/>` which resulted in an invalid XML file.

**Comment by lcerrato** [comment]
@TickleForce 
Thank you!
The testing regime should have caught the error but it slipped past me. The correction has been made.
