### ISSUE TITLE
(tlg0008.tlg001.perseus-eng3) status?

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/canonical-greekLit#1381]
@AlisonBabeu 
Do you happen to know if the Gulick translation of Athenaeus ever released? I have an unconverted file but no record of it ever making it into P4.

https://catalog.perseus.org/cite-collections/versions/urn:cite:perseus:catver.15387.1

**Comment by AlisonBabeu** [comment]
hi @lcerrato I don't believe it did because the last years of the translation weren't in the public domain.

**Comment by lcerrato** [comment]
@AlisonBabeu 
Then we would not have published the Greek, right? Volume 7 of the Greek is included. It's a print date, not a publication/copyright date.
https://archive.org/details/deipnosophists0007athe/page/n7/mode/2up

**Comment by AlisonBabeu** [comment]
@lcerrato 
I suppose we would not have then and yes it is a print date. Isn't this the text though, I think I am missing something:
http://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:2013.01.0003

**Comment by lcerrato** [comment]
@AlisonBabeu 
Nope, that's the other translation, Yonge. = tlg0008.tlg001.perseus-eng2.xml (bumped from tlg0008.tlg001.perseus-eng1)

The file I'm looking at is tlg0008.tlg001.perseus-eng3.xml (not bumped)

**Comment by lcerrato** [comment]
@AlisonBabeu 
I actually think I want to move this over to lost and found because 1) it's huge and messy and there's no point to it being here if it's not on P4 2) it's going to skew the completion stats if it just sticks around here
What do you think? Just want to be sure not to break anything.

**Comment by AlisonBabeu** [comment]
hey @lcerrato that won't break anything on the catalog end, I just have a metadata record of it linking to an XML file that I can delete.

**Comment by lcerrato** [comment]
@AlisonBabeu 
To the file name or to a file name within a repo? Because the file will still exist.

**Comment by AlisonBabeu** [comment]
@hi Lisa that is because it was in newer metadata (findable only in the GitHub repo) not in the online interface.
