### ISSUE TITLE
tlg0003.tlg001 - typo in scaife

### ISSUE THREAD

**Issue by gregorycrane** [PerseusDL/canonical-greekLit#1391]
https://scaife-dev.perseus.org/library/passage/urn:cts:greekLit:tlg0003.tlg001.perseus-grc2:6.16/xml/

‘καὶ προσήκει μοι μᾶλλον ἑτέρων, ὦ Ἀθηναῖοι, ἄρχειν              ʽἀνάγκη

should be

ἄρχειν· ἀνάγκη

**Comment by gregorycrane** [comment]
Actually, its the parenthesis disaster from the beta code conversion. So it should be

ἄρχειν (ἀνάγκη γὰρ ἐντεῦθεν ἄρξασθαι, ἐπειδή μου Νικίας καθήψατο)

**Comment by lcerrato** [comment]
@gregorycrane 
Do you think there may be others lurking in the file? Usually there are.

**Comment by lcerrato** [comment]
There are +350 parentheses in the original file, with at least +250 bad conversions lurking in this file.
