### ISSUE TITLE
(tlg0062) -- why does Lucian stop at work 52, rather than go to the end

### ISSUE THREAD

**Issue by gregorycrane** [PerseusDL/canonical-greekLit#1432]
https://scaife.perseus.org/library/urn:cts:greekLit:tlg0062/ 

There was an issue on tlg0062.tlg071 last year https://github.com/PerseusDL/canonical-greekLit/issues/1342 but I don't see anything online past work 51. 

I see in Perseus canonical-greeklit through tlg071.

NB: this got reentered in First1KGreek -- badly. The Perseus version was (I think) better -- and is often the same edition.

**Comment by gregorycrane** [comment]
Ok, I see that the later files do not yet parse in canonical-greekLit -- they still have TEI.2 dtds and have not yet been updated.

Helma must have seen the problem in tlg071 directly from the github file.

**Comment by lcerrato** [comment]
@gregorycrane 
The Perseus versions were very rough OCR—lots of irregularities.
All of Perseus Lucian has been updated now.

See https://github.com/PerseusDL/canonical-greekLit/pull/1424
https://github.com/PerseusDL/canonical-greekLit/actions/runs/4920836665/jobs/8790043613

**Comment by gregorycrane** [comment]
My local github was stuck at an earlier version. I fixed that and I see that I have updated files for all of Lucian.

Now we just need to get Scaife updated!
