### ISSUE TITLE
(tlg0655.tlg001) file not in Scaife or release package

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/canonical-greekLit#1449]
Even though this is passing all tests, there seems to be some silent error preventing it from release.

**Comment by lcerrato** [comment]
@AlisonBabeu 
The reason it doesn't load is there is no workgroup cts file.

**Comment by AlisonBabeu** [comment]
Well duh @lcerrato why didn't I think of that! :)

**Comment by lcerrato** [comment]
@AlisonBabeu It took me a while, but I looked at the logs and saw that the build removed the work metadata as well as the text file itself from the build, so that's when I saw it. There are probably others like that.

**Comment by AlisonBabeu** [comment]
hey @lcerrato is there a way for us to systematically search for this or is this something for me to bring up at the developer's meeting?

**Comment by lcerrato** [comment]
@AlisonBabeu 
I would say if we look at the release packages, Create Release > Prepare Tag
that log gives you a list of files that are being deleted from the package (non-compliant). (Under removed failing files.)

https://pipelines.actions.githubusercontent.com/serviceHosts/81ac2549-24d3-4b6a-b100-8eb438601f93/_apis/pipelines/1/runs/288/signedlogcontent/15?urlExpires=2023-06-12T17%3A55%3A34.8878051Z&urlSigningMethod=HMACV1&urlSignature=zK4HFnqC1jtmQzsYFVquUKzSgrhiACwLzq2pw1GnHzU%3D

Anything in that list that has cts metadata and/or ends in a digit higher than 1 would be something worth looking at.

**Comment by lcerrato** [comment]
@AlisonBabeu 
I don't see anything on this list that should be in the SV based on this info.

**Comment by AlisonBabeu** [comment]
hey @lcerrato how about some of those files with grc-2 or the cts_.xml files, there is a group of them under Aristotle (tlg0086), why are those being dropped?  Are those places where Scaife had absorbed files that were not yet ctsized and made Epidoc compliant.

**Comment by lcerrato** [comment]
That one is failing because the edition file name is urn:cts:greekLit:tlg0086.**tlg0045**.perseus-grc2
but it is not correctly cts-ized either (missing Bekker page sections, bad header).

**Comment by AlisonBabeu** [comment]
hey @lcerrato man that double 00!  Thanks for explaining!
