### ISSUE TITLE
(tlg0003.tlg001) missing sections (still!) in our Thuc OCT

### ISSUE THREAD

**Issue by gregorycrane** [PerseusDL/canonical-greekLit#1472]
Amazing that these are still missing. It might be easier for Lisa to add these directly but I am happy to make a pull request. Whatever is simplest.

The missing sections were detected by comparing sections in a Latin edition. I think manually compared the OCT. In most cases, there was a missing section but the Latin Didot does seem to have had a few more sections than the OCT. I left the sections that I did not find in the OCT here (they don't have accompanying images) in case I missed something. 

I actually am tempted to add the extra sections ... the more sections, the finer the granularity of citation.

nosect 1.11.3
![image](https://github.com/PerseusDL/canonical-greekLit/assets/5159577/6b7a43d8-ae8f-48d2-9d58-1f2a3649e11c)

nosect 1.38.6
![image](https://github.com/PerseusDL/canonical-greekLit/assets/5159577/c7ca6081-7118-449c-9ad3-e4842c26a6c2)

nosect 1.65.3
![image](https://github.com/PerseusDL/canonical-greekLit/assets/5159577/fda66468-0618-43ea-90cd-a9f112f39dd4)

nosect 1.105.7
nosect 1.110.5
![image](https://github.com/PerseusDL/canonical-greekLit/assets/5159577/ca0cad11-5c65-4292-bc2f-2732ee812f87)

nosect 1.138.7
nosect 1.144.5
nosect 3.3.6
![image](https://github.com/PerseusDL/canonical-greekLit/assets/5159577/feefdaa5-96b9-44b5-adac-f3bf6bb61962)

nosect 3.40.8
![image](https://github.com/PerseusDL/canonical-greekLit/assets/5159577/ddf33109-3cab-48d2-a02c-214de8606e06)

nosect 3.85.4
![image](https://github.com/PerseusDL/canonical-greekLit/assets/5159577/cfeb5998-09c3-4e3e-a03a-677d9451b2cb)

nosect 4.32.5
nosect 4.71.3
nosect 4.80.6
nosect 4.102.4
![image](https://github.com/PerseusDL/canonical-greekLit/assets/5159577/2672bde5-ad72-41d0-9a4b-181291bf317c)

nosect 4.108.8
nosect 6.23.4

**Comment by lcerrato** [comment]
Note in process

**Comment by lcerrato** [comment]
8 changes have been checked in

1. 1.11.3
2. 1.38.6
3. 1.65.3
4. 1.110.5
5. 3.3.6
6. 3.40.8
7. 3.85.4
8. 4.102.4
