### ISSUE TITLE
(tlg0061) __cts__.xml files

### ISSUE THREAD

**Issue by gregorycrane** [PerseusDL/canonical-greekLit#1498]
Hooktest is objecting to the __cts__.xml files. I can't see the problem. Can anyone else?
+---------------------------------+------------------------------+
|             Filename            |         Failed Tests         |
+---------------------------------+------------------------------+
| data/tlg0061/tlg001/__cts__.xml | Metadata availability failed |
+---------------------------------+------------------------------+
| data/tlg0061/tlg003/__cts__.xml | Metadata availability failed |
+---------------------------------+------------------------------+
| data/tlg0061/tlg004/__cts__.xml | Metadata availability failed |
+---------------------------------+------------------------------+
| data/tlg0061/tlg006/__cts__.xml | Metadata availability failed |
+---------------------------------+------------------------------+

**Comment by AlisonBabeu** [comment]
hey @gregorycrane I looked at the files and it all seems to be consistent at this point so no idea.Perhaps a fresh set of eyes on Monday!

**Comment by lcerrato** [comment]
appears fixed via https://github.com/PerseusDL/canonical-greekLit/pull/1499
