### ISSUE TITLE
(tlg0006.tlg017) foreign tag

### ISSUE THREAD

**Issue by sd80250** [PerseusDL/canonical-greekLit#1518]
Only tlg017 among the XML files of tlg0006 uses the foreign tag as a way to mark words split between lines. For consistency's sake, and for the sake of obtaining the correct line divisions without hassle, the XML should be standardized with the rest of the corpus.

An example of the `<foreign>` tag in use in tlg017:
`<l xml:base="urn:cts:greekLit:tlg0006.tlg017.perseus-grc2" n="431">τὸ φαυλότερον ἐνόμισε χρῆταί <note resp="perseus">word split in text <foreign xml:lang="grc">χρῆ-ταί</foreign></note></l>`

Another example:
```
<l xml:base="urn:cts:greekLit:tlg0006.tlg017.perseus-grc2" n="66">Βρομίῳ πόνον ἡδὺν κάματόν τʼ εὐκάματον, <note resp="perseus">lines 66-70 split differently to acocunt for hyphenated words. Print reads <foreign xml:lang="grc">Βρομίῳ πόνον ἡδὺν || κάματόν τ’ εὐκάματον, Βάκ-||χιον εὐαζομένα.|| τίς ὁδῷ τίς ὁδῷ; τίς; || μελάθροις ἔκτοπος ἔστω, στόμα τ’ εὔφη-||μον ἅπας ἐξοσιούσθω· </foreign></note></l>
<l xml:base="urn:cts:greekLit:tlg0006.tlg017.perseus-grc2" n="67">Βάκχιον εὐαζομένα.</l>
<l xml:base="urn:cts:greekLit:tlg0006.tlg017.perseus-grc2" n="68">τίς ὁδῷ τίς ὁδῷ; τίς;</l>
<l xml:base="urn:cts:greekLit:tlg0006.tlg017.perseus-grc2" n="69">μελάθροις ἔκτοπος ἔστω, στόμα τʼ εὔφημον</l>
<l xml:base="urn:cts:greekLit:tlg0006.tlg017.perseus-grc2" n="70"> ἅπας ἐξοσιούσθω·</l>
```

**Comment by lcerrato** [comment]
@sd80250 
Thank you for this.
I believe I unspilt the lines to allow for morphological word analysis and other word-based tools. I can certainly revisit.
The split is indicated by a foot note not a foreign tag per se.
Another option would be to use a choice tag or to note every line.
