### ISSUE TITLE
Python 3.12 is not working with HookTest Actions

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/canonical-greekLit#1520]
@jacobwegner 
It looks like python 3.12 is breaking the Hook Test Actions? This seems to be the key difference between last passing tests and current failing tests.
Should the https://github.com/PerseusDL/canonical-greekLit/blob/master/.github/workflows/ci.yml be set to only 3.11?
FYI @AlisonBabeu

**Comment by jacobwegner** [comment]
@lcerrato agreed; see #1521 

I am beginning to work on a utility that could eventually allow us to migrate away from hooktest, but pinning the Python version should work for now.
