### ISSUE TITLE
(tlg0012.tlg001.perseus-grc2.xml) quote review and other updates

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/canonical-greekLit#156]
adding to missing info in header
updating logs
reviewing quotes per #153

**Comment by lcerrato** [comment]
@gregorycrane Is there a reason the quotation marks aren't used? They are in print.

**Comment by gregorycrane** [comment]
@lcerrato Can you give me an example? I don't know where you would expect the quotation marks.

**Comment by lcerrato** [comment]
I think I was confused by some inconsistencies in the old text DB and the interface display. I withdraw the question!
