### ISSUE TITLE
hyphenated line numbers

### ISSUE THREAD

**Issue by gregorycrane** [PerseusDL/canonical-greekLit#158]
In drama, we get composite line numbers (e.g., we will see a citation such as "532-534". The Hyphen is illegal in CTS. 

how do we do this? We could use a "_" or the like but we should have a standardized convention.

Run at 2016-09-20 17:26:05
Testing /tlg0006/tlg005/tlg0006.tlg005.perseus-grc2.xml
File parsing passed
Parsed
URN informations passed
Naming conventions passed
RefsDecl parsing passed
1 citation's level found
Passage level parsing failed
1435 found
Reference with forbidden characters found: '532-533' '532-534' '532-536' '532-537' '532-538' '532-539' '540-541' '542-543' '758-759' '760-761' '770-771' '772-773' '1104-1105' '1106-1107' '1128-1129' '1139-1140'
Unique nodes found by XPath passed
Available in inventory failed
Epidoc DTD validation passed

**Comment by PonteIneptique** [comment]
For now, we use 532a if 532 spans over multiple speakers and `<l>`. eg : 

```xml
<div>
<said>
<speaker>Someone</speaker>
<l n="1">Something</l>
</said>
<said>
<speaker>Someone</speaker>
<l n="1">Something</l>
</said>
</div>
```
should be

```xml
<div>
<said>
<speaker>Someone</speaker>
<l n="1">Something</l>
</said>
<said>
<speaker>Someone</speaker>
<l n="1">Something</l>
</said>
</div>
```

Can you provide an example (like 532-533) using the following ?
```
\`\`\`xml
<yourxml />
\`\`\`
```

**Comment by lcerrato** [comment]
Hi, I believe in https://github.com/PerseusDL/canonical-greekLit/pull/129
we decides to use the castList in conjunction with `who` as it was decided not to alternate between speaker and said.
So
`<l n="1418">`
`<said who="Θησεύς">πρόβαινε.</said>`
`<said who="Ἡρακλῆς">χαῖρʼ, ὦ πρέσβυ.</said>`
`<said who="Ἀμφιτρύων">καὶ σύ μοι, τέκνον.</said>`
`</l>`

**Comment by lcerrato** [comment]
This issue appears not to be applicable to this repo (it is not work specific and the work to which it refers is not in this repo at all).
I have referenced recreated it in the repo for general questions  https://github.com/PerseusDL/tei-conversion-tools/issues as noted in the instructions here:
https://github.com/PerseusDL/tei-conversion-tools/wiki/Questions-and-Decisions,-Asking-and-Reaching
