### ISSUE TITLE
(urn:cts:greekLit:tlg0062.tlg031) typo in title

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/canonical-greekLit#1594]
user report MH20240302

I could not find Lucianus' Philopseudes in Perseus, but it turns out that Perseus has misspelled the name as Philopsuedes. Please correct :-)

I believe this extends all the way back to Perseus 4 so it may also apply to catalog names as well.

**Comment by AlisonBabeu** [comment]
hi @lcerrato hard to believe that typo lived in the data for so long! I fixed it in catalog data via https://github.com/PerseusDL/catalog_data/commit/454389de7164d88285da4867a788c41bfe144ddb
