### ISSUE TITLE
Report an issue: urn:cts:greekLit:tlg0016.tlg001.perseus-grc2:7.220

### ISSUE THREAD

**Issue by Iain1954** [PerseusDL/canonical-greekLit#1654]
[tlg0016.tlg001.perseus-grc2.xml](https://github.com/PerseusDL/canonical-greekLit/tree/d0a5233/data/tlg0016/tlg001/tlg0016.tlg001.perseus-grc2.xml)

wrong gender in Greek text (Book 7 chapter 220, line 20) of the prophecy given to the Spartans at the outset of the war.

“Either Sparta would be destroyed or their king would die”

The definite article before “Basilea” should be “ton” ie. tau, omicron, nu.

**Comment by lcerrato** [comment]
7.220.3: ἢ τὴν βασιλέα
https://scaife.perseus.org/reader/urn:cts:greekLit:tlg0016.tlg001.perseus-grc2:7.220?right=perseus-eng2&highlight=%40τὴν%5B4%5D

attested here: https://archive.org/details/historiesvolumei00hero_574/page/536/mode/2up?view=theater

but not in the OCT. (τὸν)

**Comment by Iain1954** [comment]
Thank you for your prompt reply.
I do understand that Perseus uses the out of copyright Loeb text. However, I think that is why the mistake appears in the Herodotus text at this point. (Book 7, 220.3 )
It is the king Leonidas who is about to die at Thermopylae. The female gender here is simply wrong. It does not agree with the masculine accusative noun “basilea”.
I report this simply as a suggested textual emendation. The fact that the OCT has the reading “ton” should indicate that this is indeed typo in the Loeb. The OCT does not show the feminine reading as an alternative in another manuscript in the critical apparatus at the foot of the page.
On a positive note, I am enjoying using the Scaife text very much.
Best wishes,
Iain Crosbie

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Iain1954** [comment]
😎
