### ISSUE TITLE
tlg0086.tlg034 -- digicorp-grc2.xml vs 1st1k-grc1.xml

### ISSUE THREAD

**Issue by gregorycrane** [PerseusDL/canonical-greekLit#1684]
These are both based on the same source: the file from the Greco-Arabic collection.

digicorp-grc2 has sections as divs and is MUCH more useful.

the 1st1k-grc1 version only has chapters and should be removed from Scaife -- it is a duplicate and confusing.

How do we do that? We don't want to lose the file because there might be something useful in it.

**Comment by lcerrato** [comment]
It can be moved to lost and found but will always be in old archives.

**Comment by lcerrato** [comment]
@gregorycrane I believe this is in the wrong repo? You want OGL, I think?
https://github.com/OpenGreekAndLatin/First1KGreek/issues
