### ISSUE TITLE
(tlg0030.tlg001-005.grc-eng) Hyperides files have the wrong canonical identifiers

### ISSUE THREAD

**Issue by AlisonBabeu** [PerseusDL/canonical-greekLit#26]
Hi. I'm not sure how to go about addressing this entirely but when I was working on a new edition of Hyperides (tlg0030) I discovered that the TLG numbers for the works that were in classics.xml and then were used to generate the CTSURNs used in to both data.perseus.org and the Perseus Catalog are incorrect.
It looks like whoever created the file originally just assumed the TLG work numbers matched up to the order of the orations as presented in the Loeb source edition.

Currently, we have the following URNs and file structures based upon them

In Defence of Lycophron-  
urn:cts:greekLit:tlg0030.tlg001.perseus-grc1 -- Should be urn:cts:greekLit:tlg0030.tlg002.perseus-grc1 

Against Philippides
urn:cts:greekLit:tlg0030.tlg002.perseus-grc1 -- Should be urn:cts:greekLit:tlg0030.tlg004.perseus-grc1

Against Athenogenes
urn:cts:greekLit:tlg0030.tlg003.perseus-grc1 -- Should be urn:cts:greekLit:tlg0030.tlg005.perseus-grc1

In Defense of Euxenippus
urn:cts:greekLit:tlg0030.tlg004.perseus-grc1 -- Should be urn:cts:greekLit:tlg0030.tlg003.perseus-grc1 

Against Demosthenes
urn:cts:greekLit:tlg0030.tlg005.perseus-grc1 -- Should be urn:cts:greekLit:tlg0030.tlg001.perseus-grc1

The same problem of course also attaches to the English XML files and their URNs.

**Comment by lcerrato** [comment]
Qs:
Has there been a fix to the catalog data itself?
As this change affect anyone who has used the stable URN in the meantime, is it something that we should fix? I'm just wondering if keeping it as-is is the better approach for internal consistency.

**Comment by lcerrato** [comment]
I think this has become a question of whether we want to de-stablize the "stable IDs" to match the TLG in this case, or just stick with what we have, since the IDs have been published for a year or more. 
Do we want absolute consistency with TLG numbering? 
Is the extra work is involved (on the catalog side in particular) to achieve this worth making this change?

**Comment by sonofmun** [comment]
For me, TLG numbering is just a means to the end of having stable identifiers. If trying to follow the TLG destabilizes our identifiers, then we should forget the TLG and stick with our own IDs. The IDs themselves (should) have no semantic value. They are simply pointers to specific objects. Trying to follow the TLG numbering is trying to give the IDs a meaning that they don't have. They only have meaning in relationship to the objects that they point to.

**Comment by PonteIneptique** [comment]
I completely agree with @sonofmun here :)

**Comment by lcerrato** [comment]
Thanks, @sonofmun @PonteIneptique ! We needed to hear this from other people.
I agree as well. We already have examples where the TLG changed numbers and it might be the case that they could change again. 
We have always stressed that there is no direct relationship between the URNs and the TLG itself and changing things now seems like a lot of effort to no real end.
Shall we close this, @AlisonBabeu?

**Comment by AlisonBabeu** [comment]
The pleasure is all mine lets consider the issue closed.

**Comment by balmas** [comment]
Just want to offer my apologies as I was probably the one to get this wrong in the first place ... :(
