### ISSUE TITLE
All files derived from Perseus:text:1999.02.0060 should be moved to protected

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/canonical-greekLit#31]
All of these files need to be moved to canonical/protected asap.

Looks like some incorrect data made it's way into the migration list.

canonical-greekLit/data/tlg0031/tlg001/tlg0031.tlg001.perseus-lat1.xml
canonical-greekLit/data/tlg0031/tlg002/tlg0031.tlg002.perseus-lat1.xml
canonical-greekLit/data/tlg0031/tlg003/tlg0031.tlg003.perseus-lat1.xml
canonical-greekLit/data/tlg0031/tlg004/tlg0031.tlg004.perseus-lat1.xml
canonical-greekLit/data/tlg0031/tlg005/tlg0031.tlg005.perseus-lat1.xml
canonical-greekLit/data/tlg0031/tlg006/tlg0031.tlg006.perseus-lat1.xml
canonical-greekLit/data/tlg0031/tlg007/tlg0031.tlg007.perseus-lat1.xml
canonical-greekLit/data/tlg0031/tlg008/tlg0031.tlg008.perseus-lat1.xml
canonical-greekLit/data/tlg0031/tlg009/tlg0031.tlg009.perseus-lat1.xml
canonical-greekLit/data/tlg0031/tlg010/tlg0031.tlg010.perseus-lat1.xml
canonical-greekLit/data/tlg0031/tlg011/tlg0031.tlg011.perseus-lat1.xml
canonical-greekLit/data/tlg0031/tlg012/tlg0031.tlg012.perseus-lat1.xml
canonical-greekLit/data/tlg0031/tlg013/tlg0031.tlg013.perseus-lat1.xml
canonical-greekLit/data/tlg0031/tlg014/tlg0031.tlg014.perseus-lat1.xml
canonical-greekLit/data/tlg0031/tlg015/tlg0031.tlg015.perseus-lat1.xml
canonical-greekLit/data/tlg0031/tlg016/tlg0031.tlg016.perseus-lat1.xml
canonical-greekLit/data/tlg0031/tlg017/tlg0031.tlg017.perseus-lat1.xml
canonical-greekLit/data/tlg0031/tlg018/tlg0031.tlg018.perseus-lat1.xml
canonical-greekLit/data/tlg0031/tlg019/tlg0031.tlg019.perseus-lat1.xml
canonical-greekLit/data/tlg0031/tlg020/tlg0031.tlg020.perseus-lat1.xml
canonical-greekLit/data/tlg0031/tlg021/tlg0031.tlg021.perseus-lat1.xml
canonical-greekLit/data/tlg0031/tlg022/tlg0031.tlg022.perseus-lat1.xml
canonical-greekLit/data/tlg0031/tlg023/tlg0031.tlg023.perseus-lat1.xml
canonical-greekLit/data/tlg0031/tlg024/tlg0031.tlg024.perseus-lat1.xml
canonical-greekLit/data/tlg0031/tlg025/tlg0031.tlg025.perseus-lat1.xml
canonical-greekLit/data/tlg0031/tlg026/tlg0031.tlg026.perseus-lat1.xml
canonical-greekLit/data/tlg0031/tlg027/tlg0031.tlg027.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg001/tlg0527.tlg001.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg002/tlg0527.tlg002.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg003/tlg0527.tlg003.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg004/tlg0527.tlg004.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg005/tlg0527.tlg005.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg006/tlg0527.tlg006.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg008/tlg0527.tlg008.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg010/tlg0527.tlg010.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg011/tlg0527.tlg011.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg012/tlg0527.tlg012.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg013/tlg0527.tlg013.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg014/tlg0527.tlg014.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg015/tlg0527.tlg015.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg016/tlg0527.tlg016.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg017/tlg0527.tlg017.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg018/tlg0527.tlg018.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg019/tlg0527.tlg019.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg020/tlg0527.tlg020.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg021/tlg0527.tlg021.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg023/tlg0527.tlg023.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg024/tlg0527.tlg024.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg027/tlg0527.tlg027.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg029/tlg0527.tlg029.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg030/tlg0527.tlg030.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg031/tlg0527.tlg031.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg032/tlg0527.tlg032.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg033/tlg0527.tlg033.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg034/tlg0527.tlg034.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg036/tlg0527.tlg036.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg037/tlg0527.tlg037.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg038/tlg0527.tlg038.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg039/tlg0527.tlg039.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg040/tlg0527.tlg040.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg041/tlg0527.tlg041.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg042/tlg0527.tlg042.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg043/tlg0527.tlg043.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg044/tlg0527.tlg044.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg045/tlg0527.tlg045.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg046/tlg0527.tlg046.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg047/tlg0527.tlg047.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg048/tlg0527.tlg048.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg049/tlg0527.tlg049.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg050/tlg0527.tlg050.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg051/tlg0527.tlg051.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg053/tlg0527.tlg053.perseus-lat1.xml
canonical-greekLit/data/tlg0527/tlg056/tlg0527.tlg056.perseus-lat1.xml

**Comment by lcerrato** [comment]
please refer any questions to me directly

**Comment by balmas** [comment]
These are now in https://github.com/PerseusDL/canonical_protected
