### ISSUE TITLE
(tlg0085.tlg005) edition review

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/canonical-greekLit#321]
reviewing text display of Perseus CTS editions

**Comment by lcerrato** [comment]
fix change log
empty line containers
stage directions? these are rendered differently elsewhere

**Comment by lcerrato** [comment]
note that tlg0085.tlg005.perseus-grc2 has several issues:
http://cts.perseids.org/read/greekLit/tlg0085/tlg005/perseus-grc2

- starts on line 5 (looks like line 1 needs to be numbered explicitly)
- is broken into cards, not lines
- has no initial speaker (I believe that the first speaker only works in a couple of examples such as http://cts.perseids.org/read/greekLit/tlg0011/tlg004/perseus-grc2/1-408 where the speaker appears after `<div n="1" ...>` which is not the case in many of the plays

NB tlg0085.tlg005.opp-grc3 works better, except for the initial speaker issue. I think that because the initial speaker appears before the first line, Nemo is looking past that for the `n="1"` as none of the front matter appears either.

But we have one version broken on lines and one by card.

**Comment by lcerrato** [comment]
tlg0085.tlg005.perseus-eng4:
http://cts.perseids.org/read/greekLit/tlg0085/tlg005/perseus-eng4/0-320

- shows front matter, but beta code is not converted and there are no line breaks between cast list items.
- line numbers reset with each new speaker — not surprising as line numbers are encoded as `<l n="tr">`
- Also have an issue whereby the card resets the line numbering even though the speaker has not changed.

**Comment by lcerrato** [comment]
tlg0085.tlg005.perseus-eng3:
http://cts.perseids.org/read/greekLit/tlg0085/tlg005/perseus-eng3/1-95

- no initial speaker
- line resets

**Comment by PonteIneptique** [comment]
Hi Lisa,
Got pinged and looked at it while on the bus to my plane after the gate :')
 "(looks like line 1 needs to be numbered explicitly)“ - > yes, every line
should be numbered explicitly. This was a misconception of Tim to do card
and partial line numbering

Le 17 janv. 2017 5:44 PM, "Lisa Cerrato" <notifications@github.com> a
écrit :

**Comment by PonteIneptique** [comment]
The new numbering xslt is explicitly made for this kind of situation.

Le 18 janv. 2017 4:32 PM, "Thibault Clérice" <leponteineptique@gmail.com> a
écrit :

**Comment by lcerrato** [comment]
more work on these files as I cannot see all changes on local Nemo.
