### ISSUE TITLE
examine whether tlg0006.tlg001.perseus-grc1/2 should be moved to protected

### ISSUE THREAD

**Issue by balmas** [PerseusDL/canonical-greekLit#34]
or under a different license

**Comment by balmas** [comment]
Hi @lcerrato any thoughts about this? This is one of the texts we added to the annotsrc inventory for Perseids.  Should I pull it out?

**Comment by lcerrato** [comment]
According to GRC, these need to be replaced and cannot be released.

**Comment by balmas** [comment]
ok done for 0006.001.grc2. Should this apply to everything in this textgroup?

**Comment by lcerrato** [comment]
No, not all are Kovacs edition. I'm referring to the notes GRC added on the P4 to P5 Text Migration List.
