### ISSUE TITLE
typos on http://cts.perseids.org/read/greekLit/tlg0553/tlg001/1st1K-grc1/5.prooimion-5.19

### ISSUE THREAD

**Issue by aniseferreira** [PerseusDL/canonical-greekLit#430]
- Ἰαθμῷ > Ἰσθμῷ
- Ἑλλιάδα > Ἑλλάδα
to be continued...

**Comment by lcerrato** [comment]
Moved to First 1k Greek repo.
https://github.com/OpenGreekAndLatin/First1KGreek/issues/1519
