### ISSUE TITLE
(tlg0007.tlg074) Epidoc and CTS conversion

### ISSUE THREAD

**Issue by charhoughton** [PerseusDL/canonical-greekLit#506]
I'm claiming this text group to convert

**Comment by charhoughton** [comment]
@lcerrato please bump the URNs for tlg0007.tlg074.perseus-eng1.xml, tlg0007.tlg074.perseus-eng2.xml, and tlg0007.tlg074.perseus-grc1.xml, which are the three files in this text group. Thanks!

**Comment by lcerrato** [comment]
@charhoughton Of course!
tlg0007.tlg074.perseus-grc1 is --> tlg0007.tlg074.perseus-grc2
tlg0007.tlg074.perseus-eng1 (Babbitt)  is --> tlg0007.tlg074.perseus-eng3
tlg0007.tlg074.perseus-eng2 (Goodwin)  is --> tlg0007.tlg074.perseus-eng4

**Comment by charhoughton** [comment]
Fix #510

**Comment by lcerrato** [comment]
Closed via #510
