### ISSUE TITLE
(tlg.0013.tlg006.perseus-grc2.xml) CTS and EpiDoc conversion

### ISSUE THREAD

**Issue by djwhittle** [PerseusDL/canonical-greekLit#513]
Claiming file for conversion work

**Comment by djwhittle** [comment]
@lcerrato Please bump the URN for file tlg0013.tlg006.perseus-grc2.xml

There is also an english file within tlg.0013.tlg006. In addition, I am not sure why its grc2 and not grc1, does this mean you've already worked on the file @lcerrato?

**Comment by lcerrato** [comment]
@djwhittle 
Yes, note the change log indicates that these have been converted. 

If they are visible on http://cts.perseids.org/ then the conversion has been done.

**Comment by lcerrato** [comment]
Anywhere there is still a tracking.json file in the directory likely needs conversion.
For instance, nearly all of Plutarch's Moralia needs work. (tlg007.tlg068 onward except for 074).
