### ISSUE TITLE
(tlg0086.tlg045.perseus-grc1.xml) EpiDoc and CTS conversion

### ISSUE THREAD

**Issue by djwhittle** [PerseusDL/canonical-greekLit#514]
Claiming file for conversion work

**Comment by djwhittle** [comment]
@lcerrato Please bump URN for file tlg0086.tlg0045.perseus-grc1.xml

**Comment by lcerrato** [comment]
Hi @djwhittle 
For Aristotle, you should know that we do not use Bekker pages/sections as these do have clean breaks. This may require lots of back and forth as to where to place the CTS structure.

**Comment by lcerrato** [comment]
@djwhittle 
We create our own divisions based on Bekker pages. Looks like there are three (1249-1251) referenced here.

So for now, use the Bekker pages (not lettered sections)  and I will fine tune these when I can. 

So,  there would be three sections 1249, 1250 and 1251.
`<div type="texpart" subtype="section" resp="perseus" n="1249">` etc

Note that if it reads `<milestone n="1249b" unit="bekker page"/>` or `<milestone n="26" unit="bekker line"/>` these should be preserved as

`<milestone unit="section" resp="bekker" n="1249b"/>`
`<milestone unit="line" resp="bekker" n="26"/>`

Thanks!

**Comment by lcerrato** [comment]
URN is bumped. Please use tlg0086.tlg045.perseus-grc2

**Comment by djwhittle** [comment]
@lcerrato Thanks so much! Also there is an extended section beginning with the element <respStmt>, temporarily I have just commented out the section. Should I leave it out or is there something else I should do?

**Comment by lcerrato** [comment]
I'm sorry, that didn't transmit. Enclose any tags with `

**Comment by djwhittle** [comment]
Fix #518

**Comment by lcerrato** [comment]
Note URN has an extra 0: correction made to issue title.

**Comment by lcerrato** [comment]
fixed via #518
