### ISSUE TITLE
(urn:cts:greekLit:tlg0527.tlg001.perseus-lat1) Broken link

### ISSUE THREAD

**Issue by ids1024** [PerseusDL/canonical-greekLit#558]
The link to the Online Book Initiative for the [Vulgate](http://www.perseus.tufts.edu/hopper/text?doc=urn:cts:greekLit:tlg0527.tlg001.perseus-lat1) no longer works.

It is accessible at this url: http://theobi.com/Religion/Vulgate
Or, via archive.org: https://web.archive.org/web/20030705041121/ftp.std.com/obi/Religion/Vulgate

I would send a PR, but the Latin text doesn't seem to be in this repo.

**Comment by lcerrato** [comment]
@ids1024 
Thanks for the report.
The link has been non-operational for some time, but we cannot make any updates to the current Perseus reading environment and no updates are planned.
The work is not going to be migrated to the open source repositories as we cannot account for the source edition or confirm its public domain status at this time. That is why it is not found in canonical-latinLit. Ideally we will source a better edition for which we have complete and accurate bibliographic information.
I will also log this in our Perseus 4 (www.perseus.tufts.edu) error reports as this pertains to that system.

**Comment by lcerrato** [comment]
See also https://github.com/PerseusDL/canonical-latinLit/issues/245
