### ISSUE TITLE
(tlg0020.tlg001.perseus-grc2:1@μουσάων[1]) Minor Typo Hesiod Theogony

### ISSUE THREAD

**Issue by sasansom** [PerseusDL/canonical-greekLit#568]
greekLit:tlg0020.tlg001.perseus-grc2:1@μουσάων[1]
should be
Μουσάων
per https://archive.org/details/in.ernet.dli.2015.183969/page/n123

**Comment by lcerrato** [comment]
Thank you! @sasansom
