### ISSUE TITLE
(tlg0006) work on regularizing Euripides

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/canonical-greekLit#572]
for working text list see
https://docs.google.com/spreadsheets/d/1q78rViyocGe0Uxzxt8D7fy-VDHwNzLvJFiuAkL7YU_M/edit?usp=sharing

issue for conversion as well as edition review and regularization issues

**Comment by gregorycrane** [comment]
I have added valid TEI XML versions of the Murray editions for the Euripides that we do not have in First1K: https://github.com/gregorycrane/Wolf1807/tree/master/MurrayEur

The big question is how to manage the many instances in Eur where a line is divided by two or even three speakers. If we have decided on a method for doing that, I can do the conversion.

**Comment by lcerrato** [comment]
These should probably be in Perseus, not First1k as this will make tracking the issue (here) easier as well as assisting with the workflow.  There is work already done on this issue that has been checked in but no PR has been completed.

Also, this will assist with the header revisions as well — comprehensive header revision and cts work file updates are being done as conversion is done. 
The cts file structure is already in place here, as well. 

In the end, it doesn't make much difference but it is easier for me to work in this repo, especially since there is no particular reason to put it in First1K.

Yes, there is a method, such as in the Euripides checked in on this thread.

`<sp><speaker>Odysseus</speaker> `
`<l n="640" part="I">Sprained thy ankle, standing still?</l></sp>`
`<sp><speaker>Second Half-Chorus</speaker> `
`<l n="640b" part="F">Yes, and my eyes are full of dust or ashes from somewhere or other.</l></sp>`

In general, we tried to go with line number N, then N+b, N+c, N+d, etc. This is inconsistent and has not yet been revisited so some texts just use N, N+a, N+b, etc.

(So, for example, if the print line numbering goes out of sync such as where six lines appear but the numbering indicates five, we may add N+a line to keep it in sync. This is not easy to describe).

The part attribute is a later addition and may not be found in texts converted earlier but I have been adding it in later work because it helps further distinguish between a line split across speaker versus a line where the letter has been added to maintain through numbering.

Every line requires a number and there are transformations in the https://github.com/PerseusDL/tei-conversion-tools repo we use to add those where needed.

**Comment by gregorycrane** [comment]
I have always used the part="I", part="M", part="F" method. Let me see how much I have to fix.

I defaulted to <lb/> milestones but I can go back to <l/> containers now that I know the preferred way of doing this.

**Comment by lcerrato** [comment]
The part attribute was found in a subset of P4 files but mostly in Latin so either it didn't carry over to most of the Greek drama or it was never there to begin with.

milestones are not particularly useful in these examples excepting perhaps the old Perseus card breaks

There are many plays with divs for the various metrical units as well but since the refsDecl is based on line, these have no bearing on the presentation.

**Comment by lcerrato** [comment]
note: 
The only missing files are 
tlg0006.tlg001 - tlg0006.tlg006 in the Greek

and a variety of English files (work on these is already underway since this just a matter of rolling back modernizations to the Coleridge)

**Comment by lcerrato** [comment]
bumped CTS URN for tlg0006.tlg019.perseus-grc1 to grc2

**Comment by lcerrato** [comment]
bumped eng1 to eng3

**Comment by lcerrato** [comment]
bumped urns for tlg0006.tlg018 files

**Comment by lcerrato** [comment]
bumped URNs for tlg016 and for tlg017

**Comment by lcerrato** [comment]
bumped files 015 and 014....

**Comment by lcerrato** [comment]
@AlisonBabeu 
tlg0006.tlg013.perseus-eng1 is not a Potter translation. To the extent that it's modernized, it's hard to tell, but this is much closer to Coleridge.
I have been reverting all of these back to Coleridge from O'Neill by making necessary changes. This will be reflected in the CTS files.
I'll update the CITE collections as I go.

- [ ] update CITE tables to reflect changed editions.

**Comment by lcerrato** [comment]
Need to make sure that the Lace credits read correctly. @lcerrato
