### ISSUE TITLE
tlg0013 Homeric Hymns incorrectly split and text missing

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/canonical-greekLit#63]
I noticed that 
tlg0013.tlg002.perseus-grcN.xml
is identical to 
tlg0013.tlg013.perseus-grcN.xml

These are actually 2 separate Hymns to Demeter, but it looks like 2 was copied into 13, erasing the text of 13?

[Hymn 2 to Demeter] (http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0137%3Ahymn%3D2)

[Hymn 13 to Demeter] (http://www.perseus.tufts.edu/hopper/text?doc=HH+13+&fromdoc=Perseus%3Atext%3A1999.01.0137)

**Comment by lcerrato** [comment]
I'm guessing this may be a problem with other HH where the title was the same or similar.

**Comment by balmas** [comment]
The homeric hymns are definitely in the group of texts for which Perseids introduced confusion and need cleanup.  @TDBuck or I will have to tackle this soon.

**Comment by lcerrato** [comment]
I started a review to clarify the extent of the problems. It looks like there was some confusion about similarly named hymns. I will also look at the inconsistencies in the titles, etc.
I am hoping this is limited to a couple of hymns that were overwritten.

**Comment by lcerrato** [comment]
- [x] tlg0013.tlg001.perseus-eng1.xml
- [x] tlg0013.tlg001.perseus-grc1.xml

- [x] tlg0013.tlg002.perseus-eng1.xml
- [x] tlg0013.tlg002.perseus-grc1.xml
- [x] tlg0013.tlg002.perseus-grc2.xml

- [x] tlg0013.tlg003.perseus-eng1.xml
- [x] tlg0013.tlg003.perseus-grc1.xml

- [x] tlg0013.tlg004.perseus-eng1.xml
- [x] tlg0013.tlg004.perseus-grc1.xml

- [x] tlg0013.tlg005.perseus-eng1.xml
- [x] tlg0013.tlg005.perseus-grc1.xml

- [ ] tlg0013.tlg006.perseus-eng1.xml 
- [ ] tlg0013.tlg006.perseus-grc1.xml

- [x] tlg0013.tlg007.perseus-eng1.xml
- [ ] tlg0013.tlg007.perseus-grc1.xml

- [x] tlg0013.tlg008.perseus-eng1.xml
- [x] tlg0013.tlg008.perseus-grc1.xml

- [x] tlg0013.tlg009.perseus-eng1.xml
- [x] tlg0013.tlg009.perseus-grc1.xml

- [ ] tlg0013.tlg010.perseus-eng1.xml
- [ ] tlg0013.tlg010.perseus-grc1.xml

- [x] tlg0013.tlg011.perseus-eng1.xml
- [x] tlg0013.tlg011.perseus-grc1.xml

- [x] tlg0013.tlg012.perseus-eng1.xml
- [x] tlg0013.tlg012.perseus-grc1.xml

- [ ] tlg0013.tlg013.perseus-eng1.xml
- [ ] tlg0013.tlg013.perseus-grc1.xml

- [x] tlg0013.tlg014.perseus-eng1.xml
- [x] tlg0013.tlg014.perseus-grc1.xml

- [x] tlg0013.tlg015.perseus-eng1.xml
- [x] tlg0013.tlg015.perseus-grc1.xml

- [x] tlg0013.tlg016.perseus-eng1.xml
- [x] tlg0013.tlg016.perseus-grc1.xml

- [x] tlg0013.tlg017.perseus-eng1.xml
- [x] tlg0013.tlg017.perseus-grc1.xml

- [ ] tlg0013.tlg018.perseus-eng1.xml
- [ ] tlg0013.tlg018.perseus-grc1.xml

- [x] tlg0013.tlg019.perseus-eng1
- [ ] tlg0013.tlg019.perseus-grc1 missing

- [x] tlg0013.tlg020.perseus-eng1.xml
- [x] tlg0013.tlg020.perseus-grc1.xml

- [x] tlg0013.tlg021.perseus-eng1.xml
- [x] tlg0013.tlg021.perseus-grc1.xml

- [x] tlg0013.tlg022.perseus-eng1.xml
- [x] tlg0013.tlg022.perseus-grc1.xml

- [x] tlg0013.tlg023.perseus-eng1.xml
- [x] tlg0013.tlg023.perseus-grc1.xml

- [x] tlg0013.tlg024.perseus-eng1.xml
- [x] tlg0013.tlg024.perseus-grc1.xml

- [x] tlg0013.tlg025.perseus-eng1.xml
- [x] tlg0013.tlg025.perseus-grc1.xml

- [ ] tlg0013.tlg026.perseus-eng1.xml
- [x] tlg0013.tlg026.perseus-grc1.xml

- [ ] tlg0013.tlg027.perseus-eng1.xml
- [ ] tlg0013.tlg027.perseus-grc1.xml

- [ ] tlg0013.tlg028.perseus-eng1.xml
- [ ] tlg0013.tlg028.perseus-grc1.xml

- [ ] tlg0013.tlg029.perseus-eng1.xml
- [ ] tlg0013.tlg029.perseus-grc1.xml

- [x] tlg0013.tlg030.perseus-eng1.xml
- [x] tlg0013.tlg030.perseus-grc1.xml

- [ ] tlg0013.tlg031.perseus-eng1.xml missing lines
- [x] tlg0013.tlg031.perseus-grc1.xml

- [x] tlg0013.tlg032.perseus-eng1.xml
- [x] tlg0013.tlg032.perseus-grc1.xml

- [ ] tlg0013.tlg033.perseus-eng1.xml
- [ ] tlg0013.tlg033.perseus-grc1.xml

**Comment by lcerrato** [comment]
Bad texts
- [ ] tlg0013.tlg006.perseus-eng1.xml 
- [ ] tlg0013.tlg006.perseus-grc1.xml
- [ ] tlg0013.tlg007.perseus-grc1.xml
- [ ] tlg0013.tlg010.perseus-eng1.xml
- [ ] tlg0013.tlg010.perseus-grc1.xml
- [ ] tlg0013.tlg013.perseus-eng1.xml
- [ ] tlg0013.tlg013.perseus-grc1.xml
- [ ] tlg0013.tlg018.perseus-eng1.xml
- [ ] tlg0013.tlg018.perseus-grc1.xml
- [ ] tlg0013.tlg019.perseus-grc1 : missing
- [ ] tlg0013.tlg026.perseus-eng1.xml
- [ ] tlg0013.tlg027.perseus-eng1.xml
- [ ] tlg0013.tlg027.perseus-grc1.xml
- [ ] tlg0013.tlg028.perseus-eng1.xml
- [ ] tlg0013.tlg028.perseus-grc1.xml
- [ ] tlg0013.tlg029.perseus-eng1.xml
- [ ] tlg0013.tlg029.perseus-grc1.xml
- [ ] tlg0013.tlg031.perseus-eng1.xml : missing lines
- [ ] tlg0013.tlg033.perseus-eng1.xml
- [ ] tlg0013.tlg033.perseus-grc1.xml

**Comment by lcerrato** [comment]
@AlisonBabeu Are the titles for the individual hymns in the catalog derived from Perseus or a non Perseus source? (eg "Hymn 1 to Dionysus").

**Comment by lcerrato** [comment]
reminder to readd any corrections that may have been made between P4 Greek from site and source text

**Comment by lcerrato** [comment]
tlg0013.tlg007.perseus-eng1.xml
tlg0013.tlg019.perseus-eng1.xml
tlg0013.tlg031.perseus-eng1.xml

headers were not regularized
