### ISSUE TITLE
(tlg0007.tlg081) cts work file creation

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/canonical-greekLit#683]
needs work 
@ahanhardt Looks like these were skipped? Please assign 081 group as needed. Thanks

**Comment by 1ucyP** [comment]
@lcerrato  We have been dividing up the files for the tlg0007 and keeping track on a spreadsheet (let us know if you would like us to share it with you) so nothing is skipped! I am currently working on this file and must have accidentally forgotten to claim it!
