### ISSUE TITLE
(tlg0007.tlg082) cts work file

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/canonical-greekLit#690]
needs creation

**Comment by lcerrato** [comment]
@ahanhardt 
Looks like this series was skipped, too. I'm bumping and reviewing header info in order so I'm flagging these for your attention whenever there is an opening.

**Comment by kcooper42** [comment]
@lcerrato We have been dividing up the files for the tlg0007 Moralia and keeping track on a spreadsheet (let us know if you would like us to share it with you) so nothing is skipped. I am planning on working on the tlg082 files after finishing 077, I just hadn't gotten around to creating the issues yet.
