### ISSUE TITLE
(tlg0007.tlg117.perseus-eng1.xml) EpiDoc and CTS Conversion

### ISSUE THREAD

**Issue by ahanhardt** [PerseusDL/canonical-greekLit#871]
Claiming file for conversion work

**Comment by ahanhardt** [comment]
@lcerrato please bump the URN for file tlg0007.tlg117.perseus-eng1.xml

**Comment by lcerrato** [comment]
@ahanhardt 
the Loeb Fowler translation has been bumped to eng3
